version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - employee-mgr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 10s

networks:
  employee-mgr-network:
    name: employee-mgr-network
volumes:
  postgres-data:
